function getText(element) {
  return element?.textContent?.trim() || '';
}

export default function decorate(block) {
  // Read the semantic HTML generated by AEM.
  const rows = [...block.children];

  if (!rows.length) {
    return;
  }

  // Expected authoring order:
  // 1. Image
  // 2. Heading
  // 3. CTA text
  // 4. CTA link

  //   const imageCell = rows[0]?.querySelector('picture, img');
  const headingCell = rows[1];
  const ctaTextCell = rows[2];
  const ctaLinkCell = rows[3];

  // Extract image.
  const picture = rows[0]?.querySelector('picture');
  const img = rows[0]?.querySelector('img');

  const image = picture || img;

  // Extract authored values.
  const heading = getText(headingCell);
  const ctaText = getText(ctaTextCell);
  const ctaLink = ctaLinkCell?.querySelector('a')?.href
    || getText(ctaLinkCell);

  // Clear the default table-like block markup.
  block.textContent = '';

  // Create hero content.
  const content = document.createElement('div');
  content.className = 'vida-hero-content';

  if (heading) {
    const title = document.createElement('h1');
    title.className = 'vida-hero-title';
    title.textContent = heading;
    content.append(title);
  }

  if (ctaText) {
    const cta = document.createElement('a');
    cta.className = 'vida-hero-cta';
    cta.textContent = ctaText;
    cta.href = ctaLink || '#';

    content.append(cta);
  }

  // Create image layer.
  if (image) {
    const media = document.createElement('div');
    media.className = 'vida-hero-media';

    if (picture) {
      media.append(picture);
    } else {
      media.append(img);
    }

    block.append(media);
  }

  block.append(content);
}
